export default viewActionType = {
    GET_ALL_DEBTS: "GET_ALL_DEBTS",
    GET_USER_DEBTS: "GET_USER_DEBTS",
    GET_DEBTS_SUCCESS: "FETCH_DEBTS_SUCCESS",
    GET_DEBTS_FAIL: "GET_DEBTS_FAIL",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL"
}