export default authActionType = {
    LOGIN_CHECK: "LOGIN_CHECK",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",
    LOG_OUT: "LOG_OUT",
    SET_SESSION_TOKEN: "SET_SESSION_TOKEN",
};